export const SET_LOADING = "SET_LOADING";
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";

export const FETCH_TOP_CATEGORY_REQUEST = "FETCH_TOP_CATEGORY_REQUEST";
export const FETCH_TOP_CATEGORY_SUCCESS = "FETCH_TOP_CATEGORY_SUCCESS";
export const FETCH_TOP_CATEGORY_FAILURE = "FETCH_TOP_CATEGORY_FAILURE";

export const FETCH_ALL_CATEGORY_REQUEST = "FETCH_ALL_CATEGORY_REQUEST";
export const FETCH_ALL_CATEGORY_SUCCESS = "FETCH_ALL_CATEGORY_SUCCESS";
export const FETCH_ALL_CATEGORY_FAILURE = "FETCH_ALL_CATEGORY_FAILURE";

export const FETCH_ALL_PRODUCTS_BY_CATEGORY_REQUEST =
  "FETCH_ALL_PRODUCTS_BY_CATEGORY_REQUEST";
export const FETCH_ALL_PRODUCTS_BY_CATEGORY_SUCCESS =
  "FETCH_ALL_PRODUCTS_BY_CATEGORY_SUCCESS";
export const FETCH_ALL_PRODUCTS_BY_CATEGORY_FAILURE =
  "FETCH_ALL_PRODUCTS_BY_CATEGORY_FAILURE";

export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILURE = "FETCH_PRODUCTS_FAILURE";

export const FETCH_TOPTEN_PRODUCTS_REQUEST = "FETCH_TOPTEN_PRODUCTS_REQUEST";
export const FETCH_TOPTEN_PRODUCTS_SUCCESS = "FETCH_TOPTEN_PRODUCTS_SUCCESS";
export const FETCH_TOPTEN_PRODUCTS_FAILURE = "FETCH_TOPTEN_PRODUCTS_FAILURE";

export const FETCH_PRODUCT_DETAILS_REQUEST = "FETCH_PRODUCT_DETAILS_REQUEST";
export const FETCH_PRODUCT_DETAILS_SUCCESS = "FETCH_PRODUCT_DETAILS_SUCCESS";
export const FETCH_PRODUCT_DETAILS_FAILURE = "FETCH_PRODUCT_DETAILS_FAILURE";

export const FETCH_ADD_TO_CART_REQUEST = "FETCH_ADD_TO_CART_REQUEST";
export const FETCH_ADD_TO_CART_SUCCESS = "FETCH_ADD_TO_CART_SUCCESS";
export const FETCH_ADD_TO_CART_FAILURE = "FETCH_ADD_TO_CART_FAILURE";

export const FETCH_ADD_TO_CART_UPDATE_REQUEST =
  "FETCH_ADD_TO_CART_UPDATE_REQUEST";
export const FETCH_ADD_TO_CART_UPDATE_SUCCESS =
  "FETCH_ADD_TO_CART_UPDATE_SUCCESS";
export const FETCH_ADD_TO_CART_UPDATE_FAILURE =
  "FETCH_ADD_TO_CART_UPDATE_FAILURE";

export const FETCH_REMOVE_FROM_CART_REQUEST = "FETCH_REMOVE_FROM_CART_REQUEST";
export const FETCH_REMOVE_FROM_CART_SUCCESS = "FETCH_REMOVE_FROM_CART_SUCCESS";
export const FETCH_REMOVE_FROM_CART_FAILURE = "FETCH_REMOVE_FROM_CART_FAILURE";

export const FETCH_CART_DETAILS_REQUEST = "FETCH_CART_DETAILS_REQUEST";
export const FETCH_CART_DETAILS_SUCCESS = "FETCH_CART_DETAILS_SUCCESS";
export const FETCH_CART_DETAILS_FAILURE = "FETCH_CART_DETAILS_FAILURE";

export const FETCH_WISHLIST_DETAILS_REQUEST = "FETCH_WISHLIST_DETAILS_REQUEST";
export const FETCH_WISHLIST_DETAILS_SUCCESS = "FETCH_WISHLIST_DETAILS_SUCCESS";
export const FETCH_WISHLIST_DETAILS_FAILURE = "FETCH_WISHLIST_DETAILS_FAILURE";

export const FETCH_ADD_TO_WISHLIST_REQUEST = "FETCH_ADD_TO_WISHLIST_REQUEST";
export const FETCH_ADD_TO_WISHLIST_SUCCESS = "FETCH_ADD_TO_WISHLIST_SUCCESS";
export const FETCH_ADD_TO_WISHLIST_FAILURE = "FETCH_ADD_TO_WISHLIST_FAILURE";

export const FETCH_REMOVE_FROM_WISHLIST_REQUEST =
  "FETCH_REMOVE_FROM_WISHLIST_REQUEST";
export const FETCH_REMOVE_FROM_WISHLIST_SUCCESS =
  "FETCH_REMOVE_FROM_WISHLIST_SUCCESS";
export const FETCH_REMOVE_FROM_WISHLIST_FAILURE =
  "FETCH_REMOVE_FROM_WISHLIST_FAILURE";

export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const FETCH_SIGNUP_REQUEST = "FETCH_SIGNUP_REQUEST";
export const FETCH_SIGNUP_SUCCESS = "FETCH_SIGNUP_SUCCESS";
export const FETCH_SIGNUP_FAILURE = "FETCH_SIGNUP_FAILURE";

export const FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST";
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS";
export const FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE";

export const FETCH_USER_DETAILS_REQUEST = "FETCH_USER_DETAILS_REQUEST";
export const FETCH_USER_DETAILS_SUCCESS = "FETCH_USER_DETAILS_SUCCESS";
export const FETCH_USER_DETAILS_FAILURE = "FETCH_USER_DETAILS_FAILURE";

export const FETCH_SET_USER_DATA_REQUEST = "FETCH_SET_USER_DATA_REQUEST";
export const FETCH_SET_USER_DATA_SUCCESS = "FETCH_SET_USER_DATA_SUCCESS";
export const FETCH_SET_USER_DATA_FAILURE = "FETCH_SET_USER_DATA_FAILURE";

export const FETCH_VERIFY_TOKEN_REQUEST = "FETCH_VERIFY_TOKEN_REQUEST";
export const FETCH_VERIFY_TOKEN_SUCCESS = "FETCH_VERIFY_TOKEN_SUCCESS";
export const FETCH_VERIFY_TOKEN_FAILURE = "FETCH_VERIFY_TOKEN_FAILURE";

export const FETCH_RESET_USER_PASSWORD_REQUEST =
  "FETCH_RESET_USER_PASSWORD_REQUEST";
export const FETCH_RESET_USER_PASSWORD_SUCCESS =
  "FETCH_RESET_USER_PASSWORD_SUCCESS";
export const FETCH_RESET_USER_PASSWORD_FAILURE =
  "FETCH_RESET_USER_PASSWORD_FAILURE";
export const FETCH_RESET_USER_PASSWORD_IsTrue_REQUEST =
  "FETCH_RESET_USER_PASSWORD_IsTrue_REQUEST";

export const FETCH_LOGIN_EMPTY_REQUEST = "FETCH_LOGIN_EMPTY_REQUEST";

export const FETCH_FORGOT_USER_PASSWORD_REQUEST =
  "FETCH_FORGOT_USER_PASSWORD_REQUEST";
export const FETCH_FORGOT_USER_PASSWORD_SUCCESS =
  "FETCH_FORGOT_USER_PASSWORD_SUCCESS";
export const FETCH_FORGOT_USER_PASSWORD_FAILURE =
  "FETCH_FORGOT_USER_PASSWORD_FAILURE";

// export const SET_LOADING = "SET_LOADING";
